backend_core/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend_core/home/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie

from config import settings
from . import views

app_name = 'home'

urlpatterns = [
    path('', vary_on_cookie(cache_page(settings.CACHE_TTL)(views.LandingPageView.as_view())), name='index'),
    path('add_donation/', views.DonationCreateView.as_view(), name='add-donation'),
]

backend_core/users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie

from config import settings
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.SignUpView.as_view(), name='registration'),
    path('login/', views.LogInView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', vary_on_cookie(cache_page(settings.CACHE_TTL)(views.UserProfileView.as_view())), name='user-profile'),
    path('settings/<int:pk>', views.UserSettingsView.as_view(), name='user-settings'),
    path('password_change/', views.ChangePasswordView.as_view(), name='password-change'),
    path('password_change/done/', views.ChangePasswordDoneView.as_view(), name='password-change-done'),
]

backend_core/templates/base.html
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Donate Stuff - {% block title %}{% endblock title %}</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/scroll.css' %}" />
    {% block scripts %}
        <script src="{% static 'js/app.js' %}" async defer></script>
    {% endblock %}
  </head>
  <body class="h-100">
    {% block header %}{% endblock header %}
    {% block container %}{% endblock container %}
    <footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50">
              <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
              <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2019</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"><img src="{% static 'images/icon-facebook.svg' %}"/></a>
          <a href="#" class="btn btn--small"><img src="{% static 'images/icon-instagram.svg' %}"/></a>
        </div>
      </div>
    </footer>
  </body>
</html>

backend_core/templates/form-confirmation.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Success
{% endblock title %}

  {% block header %}
    <header class="header--form-page">
      {% include 'partials/navbar.html' %}

      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
    </header>
  {% endblock header %}

backend_core/templates/form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  New Donation
{% endblock title %}

  {% block header %}
    <header class="header--form-page">
      {% include 'partials/navbar.html' %}

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>
  {% endblock header %}

  {% block container %}
    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz organizację, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
          <p data-step="5">Sprawdź czy wprowadzone przez Ciebie dane są poprawne.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span id="current_step">1</span>/5</div>
        <form id="donation-form" name="donationForm" action="{% url 'home:add-donation' %}" method="post">
          {% csrf_token %}


          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" id="step-1" class="form-steps-inputs active">
            <h3>Zaznacz co chcesz oddać:</h3>

            <div class="form-error" hidden>
                <h4 style="color: red;">Musisz wybrać przynajmniej jedną kategorię.</h4>
            </div>
            {% for category in form.categories %}
                <div class="form-group form-group--checkbox">
                  <label>
                    <input
                      class="category-choice"
                      type="checkbox"
                      name="categories"
                    />
                    <span class="checkbox"></span>
                    <span class="description"
                      >{{ category }}</span
                    >
                  </label>
                </div>
            {% endfor %}

            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2" id="step-2" class="form-steps-inputs">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-error" hidden>
                <h4 style="color: red;">Podaj poprawną ilość worków.</h4>
            </div>

            <div class="form-group form-group--inline">
              <label>
                Liczba 60l worków:
                <input id="quantity" type="number" name="quantity" step="1" min="1" />
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 3 -->
          <div data-step="3" id="step-3" class="form-steps-inputs">

            <h3>Wybierz organizację, której chcesz pomóc:</h3>

            <div class="form-error" hidden="hidden">
                <h4 style="color: red;">Wybierz instytucję, której chcesz przekazać dary.</h4>
            </div>

            {% for institution in form.institution %}
                <div class="form-group form-group--checkbox">
                  <label>
                    <input class="institution-choice" type="radio" name="institution" value="old" />
                    <span class="checkbox radio"></span>
                    <span class="description">
                      <div class="title">{{ institution }}</div>
                      <div class="subtitle">
                        {{ institution.description }}
                      </div>
                    </span>
                  </label>
                </div>
            {% endfor %}

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 4 -->
          <div data-step="4" id="step-4" class="form-steps-inputs">
            <h3>Podaj adres oraz termin odbioru rzeczy przez kuriera:</h3>

            <div class="form-error" hidden>
                <h4 style="color: red;">Pola oznaczone gwiazdką są obowiązkowe.</h4>
            </div>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica* <input id="address" type="text" name="address" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto* <input id="city" type="text" name="city" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy* <input id="zip_code" type="text" name="zip_code" />
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu* <input id="phone_number" type="text" name="phone_number" />
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data* <input id="pickupdate" type="date" name="pick_up_date" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina* <input id="pickuptime" type="time" name="pick_up_time" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    <textarea id="comment" name="pick_up_comment" rows="5"></textarea>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step get-form-data">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="5" id="step-5" class="form-steps-inputs">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span id="donation_info" class="summary--text"
                      >5 worków ubrań</span
                    >
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span id="don_institution" class="summary--text"
                      >Dla fundacji "Mam marzenie" w Warszawie</span
                    >
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                    <li id="don_address"></li>
                    <li id="don_city"></li>
                    <li id="don_zip_code"></li>
                    <li id="don_phone"></li>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                    <li id="don_date"></li>
                    <li id="don_time">15:40</li>
                    <li id="don_comment">Brak uwag</li>
                  </ul>
                </div>
              </div>
            </div>

            <button class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
                <input type="submit" class="btn" value="Potwierdzam">
            </button>
            </div>

            <div data-step="6" id="step-6" class="form-steps-input">
                <h1>Dziękujemy za przekazanie darowizny. Za chwilę zostaniesz przekierowany na stronę główną.</h1>
            </div>
          </div>
        </form>
      </div>
    </section>
  {% endblock container %}

backend_core/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% load cache %}

{% block title %}
  Welcome
{% endblock title %}

  {% block header %}
    <header class="header--main-page">
      {% include 'partials/navbar.html' %}

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Zacznij pomagać!<br />
            Oddaj niechciane rzeczy w zaufane ręce
          </h1>
        </div>
      </div>
    </header>
  {% endblock header %}


  {% block container %}
    <section id="stats" class="stats">
      <div class="container container--85">
        <div class="stats--item">
          <em>{{ bags_count }}</em>
          <h3>Oddanych worków</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum tempora!</p>
        </div>

        <div class="stats--item">
          <em>{{ inst_count }}</em>
          <h3>Wspartych organizacji</h3>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate quas quam.</p>
        </div>

      </div>
    </section>

    <section id="steps" class="steps">
      <h2>Wystarczą 4 proste kroki</h2>

      <div class="steps--container">
        <div class="steps--item">
          <span class="icon icon--hands"></span>
          <h3>Wybierz rzeczy</h3>
          <p>ubrania, zabawki, sprzęt i inne</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--arrow"></span>
          <h3>Spakuj je</h3>
          <p>skorzystaj z worków na śmieci</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--glasses"></span>
          <h3>Zdecyduj komu chcesz pomóc</h3>
          <p>wybierz zaufane miejsce</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--courier"></span>
          <h3>Zamów kuriera</h3>
          <p>kurier przyjedzie w dogodnym terminie</p>
        </div>
      </div>

      <a href="{% url 'users:registration' %}" class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
      <div class="about-us--text">
        <h2>O nas</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt libero optio esse quisquam illo omnis.</p>
        <img src="{% static 'images/signature.svg' %}" class="about-us--text-signature" alt="Signature" />
      </div>
      <div class="about-us--image"><img src="{% static 'images/about-us.jpg' %}" alt="People in circle" /></div>
    </section>

     <section id="help" class="help">
      <h2>Komu pomagamy?</h2>

      <ul class="help--buttons">
        <li data-id="1"><a href="#help" class="btn btn--without-border active">Fundacjom</a></li>
        <li data-id="2"><a href="#help" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
        <li data-id="3"><a href="#help" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
      </ul>

      {% for group in institutions %}
      <div class="help--slides {% if group.0 == 1 %}active{% endif %}" data-id="{{ group.0 }}">
        <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy.
          Możesz sprawdzić czym się zajmują, komu pomagają i czego potrzebują.</p>

        <ul class="help--slides-items">
          {% for institution in group.1 %}
          <li>
            <div class="col">
              <div class="title">{{ institution.name }}</div>
              <div class="subtitle">{{ institution.description }}</div>
            </div>

            <div class="col">
              <div class="text">
                {% for category in institution.categories.all %}
                  {{ category }},
                {% endfor %}
              </div>
            </div>

          </li>
          {% endfor %}
        </ul>
        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
        </ul>
        -->
      </div>
     {% endfor %}
        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="4">4</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="5">5</a></li>
        </ul>
        -->
    </section>
  {% endblock container %}

backend_core/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Login
{% endblock title %}

{% block header %}
    <header>
      {% include 'partials/navbar.html' %}
    </header>
{% endblock header %}

{% block container %}
    <section class="login-page">
      <h2>Zaloguj się</h2>
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.username }}
        </div>
        <div class="form-group">
          {{ form.password }}
          <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
        </div>

        <div class="form-group form-group--buttons">
          <a href="{% url 'users:registration' %}" class="btn btn--without-border">Załóż konto</a>
          <button class="btn" type="submit">Zaloguj się</button> 
        </div>
      </form>
    </section>
{% endblock container %}

backend_core/templates/password-change-done.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Hasło zmienione
{% endblock title %}

{% block header %}
    <header class="">
        {% include 'partials/navbar.html' %}
    </header>
{% endblock header %}

{% block container %}
    <h2>Hasło zmienione pomyślnie.</h2>
{% endblock container %}

backend_core/templates/password-change.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Zmień hasło
{% endblock title %}

{% block header %}
    <header class="">
        {% include 'partials/navbar.html' %}
    </header>
{% endblock header %}

{% block container %}
    <section class="login-page">
      <h2>Zmień hasło</h2>
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
          {{ form.old_password }}
        </div>
        <div class="form-group">
          {{ form.new_password1 }}
        </div>
        <div class="form-group">
          {{ form.new_password2 }}
        </div>
        <div class="form-group form-group--buttons">
          <a href="{% url 'users:user-profile' %}" class="btn btn--without-border">Anuluj</a>
          <button class="btn" type="submit">Zatwierdź zmiany</button>
        </div>
      </form>
    </section>
{% endblock container %}

backend_core/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Register
{% endblock title %}

  {% block header %}
    <header>
      {% include 'partials/navbar.html' %}
    </header>
  {% endblock header %}

  {% block container %}
    <section class="login-page">
      <h2>Załóż konto</h2>
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
          {{ form.first_name }}
        </div>
         <div class="form-group">
          {{ form.last_name }}
        </div>
        <div class="form-group">
          {{ form.email }}
        </div>
        <div class="form-group">
          {{ form.password }}
        </div>
        <div class="form-group">
          {{ form.password_confirmation }}
        </div>
        <div class="form-group form-group--buttons">
          <a href="{% url 'users:login' %}" class="btn btn--without-border">Zaloguj się</a>
          <button class="btn" type="submit">Załóż konto</button>
        </div>
      </form>
    </section>
  {% endblock container %}

backend_core/templates/user-page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ user.first_name }} {{ user.last_name }}
{% endblock title %}

{% block scripts %}
    <script src="{% static 'js/archive.js' %}" async defer></script>
{% endblock %}

{% block header %}
    <header class="">
        {% include 'partials/navbar.html' %}
    </header>
{% endblock header %}

{% block container %}
    <section id="help" class="help" style="margin-bottom: 0; padding-bottom: 0;">
      <h2>{{ user.first_name }} {{ user.last_name }}</h2>
      <h1>Kontakt: {{ user.email }}</h1>

      <h1>Twoje darowizny:</h1>
      <div class="scroll-container">
        {% for donation in donations %}
            <button type="button" class="collapsible" id="{{ donation.id }}">
                {% if donation.is_taken %}
                    {{ donation }} (DOSTARCZONE)
                {% else %}
                    <strong>{{ donation }}</strong>
                {% endif %}
            </button>
                <div class="content" style="justify-content: space-between;">
                <div class="w-50" style="text-align: left;">
                    <p><strong>Data i godzina odbioru:</strong></p>
                    <p><strong>Dla:</strong></p>
                    <p><strong>Typ instytucji:</strong></p>
                    <p><strong>Kategorie darowanych przedmiotów:</strong></p>
                    <p><strong>Ilość worków:</strong></p>
                    <p><strong>Telefon kontaktowy:</strong></p>
                    <p><strong>Adres:</strong></p>
                    <p><strong>Kod pocztowy:</strong></p>
                    <p><strong>Miasto:</strong></p>
                    {% if donation.pick_up_comment %}
                        <p><strong>Dodatkowe uwagi:</strong></p>
                    {% endif %}
                </div>
                <div class="w-50" style="text-align: right; padding-bottom: 10px;">
                    <p>{{ donation.pick_up_date }} {{ donation.pick_up_time }}</p>
                    <p>{{ donation.institution.name }}</p>
                    <p>{{ donation.institution.get_type_display }}</p>
                    <p>
                        {% for category in donation.categories.all %}
                            {{ category.name }}
                        {% endfor %}
                    </p>
                    <p>{{ donation.quantity }}</p>
                    <p>{{ donation.phone_number }}</p>
                    <p>{{ donation.address }}</p>
                    <p>{{ donation.zip_code }}</p>
                    <p>{{ donation.city }}</p>
                    {% if donation.pick_up_comment %}
                        <p>{{ donation.pick_up_comment }}</p>
                    {% endif %}
                    {% if not donation.is_taken %}
                        {% if today < donation.pick_up_date %}
                        {% else %}
                            {% csrf_token %}
                            <button type="button" class="archive d-none" value="{{ donation.id }}">Dostarczone!</button>
                        {% endif %}
                    {% endif %}
                </div>
          </div>
        {% endfor %}
      </div>
    </section>

    <section id="stats" class="stats" style="margin-bottom: 0; ">
          <div class="stats--item">
              <h2>Twoje statystyki</h2>
          </div>
          <div class="container container--85">
              <div class="stats--item">
                  <em>{{ bags_count }}</em>
                  <h3>Oddanych worków</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum tempora!</p>
              </div>

              <div class="stats--item">
                  <em>{{ inst_count }}</em>
                  <h3>Wspartych organizacji</h3>
                  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate quas quam.</p>
              </div>
          </div>
        </section>
{% endblock container %}

backend_core/templates/user-settings.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Ustawienia użytkownika
{% endblock title %}

{% block header %}
    <header class="">
        {% include 'partials/navbar.html' %}
    </header>
{% endblock header %}

{% block container %}
    <section class="login-page">
      <h2>Ustawienia konta</h2>
      <form action="/users/settings/{{ user.id }}" method="post">
        {% csrf_token %}
        <div class="form-group">
          {{ form.first_name }}
        </div>
         <div class="form-group">
          {{ form.last_name }}
        </div>
        <div class="form-group">
          <a href="{% url 'users:password-change' %}" class="btn">Zmień hasło</a>
        </div>
        <div class="form-group form-group--buttons">
          <a href="{% url 'users:user-profile' %}" class="btn btn--without-border">Anuluj</a>
          <button class="btn" type="submit">Zatwierdź zmiany</button>
        </div>
      </form>
    </section>
{% endblock container %}