backend_core/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend_core/home/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie

from config import settings
from . import views

app_name = 'home'

urlpatterns = [
    path('', vary_on_cookie(cache_page(settings.CACHE_TTL)(views.LandingPageView.as_view())), name='index'),
    path('add_donation/', views.DonationCreateView.as_view(), name='add-donation'),
]

backend_core/users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie

from config import settings
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.SignUpView.as_view(), name='registration'),
    path('login/', views.LogInView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', vary_on_cookie(cache_page(settings.CACHE_TTL)(views.UserProfileView.as_view())), name='user-profile'),
    path('settings/<int:pk>', views.UserSettingsView.as_view(), name='user-settings'),
    path('password_change/', views.ChangePasswordView.as_view(), name='password-change'),
    path('password_change/done/', views.ChangePasswordDoneView.as_view(), name='password-change-done'),
]

backend_core/templates/partials/navbar.html
{% load static %}

<nav class="container container--70">
    <ul class="nav--actions">
        {% if user.is_authenticated %}
            <li class="logged-user">
                Witaj {{ user.first_name }}
                <ul class="dropdown">
                  <li><a href="{% url 'users:user-profile' %}">Profil</a></li>
                  <li><a href="{% url 'users:user-settings' pk=user.id %}">Ustawienia</a></li>
                    {% if user.is_superuser %}
                        <li><a href="/admin">Panel administracyjny</a></li>
                    {% endif %}
                  <li><a href="{% url 'users:logout' %}">Wyloguj</a></li>
                </ul>
            </li>
        {% else %}
            <li><a href="{% url 'users:login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
            <li><a href="{% url 'users:registration' %}" class="btn btn--small btn--highlighted">Załóż konto</a></li>
        {% endif %}
    </ul>
    <ul>
        <li><a href="{% url 'home:index' %}" class="btn btn--highlighted">Start</a></li>
        <li><a href="{% url 'home:index' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
        <li><a href="{% url 'home:index' %}#about-us" class="btn btn--without-border">O nas</a></li>
        <li><a href="{% url 'home:index' %}#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
        <li><a href="{% url 'home:add-donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
        <li><a href="{% url 'home:index' %}#contact" class="btn btn--without-border">Kontakt</a></li>
    </ul>
</nav>